@echo off

set VEH_TYPE=vehicle
set DEBUG_FLAG=False
set SUBSAMPLED_FLAG=True

set DATE=2025-06-16


set INTERSECTION=D1
set CODE=A
for %%S in (AM1 AM2 AM3 AM4 AM5 AM6 PM1 PM2 PM3 PM4 PM5 PM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)

@REM set INTERSECTION=D3
@REM set CODE=E
@REM for %%S in (AM1 AM2 AM3 AM4 AM5 AM6 PM1 PM2 PM3 PM4 PM5 PM6) do (
@REM     echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM     python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM )

@REM set INTERSECTION=D4
@REM set CODE=F
@REM for %%S in (AM1 AM2 AM3 AM4 AM5 AM6 PM1 PM2 PM3 PM4 PM5 PM6) do (
@REM     echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM     python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM )

GOTO:skip1
set INTERSECTION=D2
set CODE=G
for %%S in (AM1 AM2 AM3 AM4 AM5 AM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)

set INTERSECTION=D2
set CODE=C
for %%S in (PM1 PM2 PM3 PM4 PM5 PM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)
:skip1



set DATE=2025-06-17


set INTERSECTION=D1
set CODE=A
for %%S in (AM1 AM2 AM3 AM4 AM5 AM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)

set INTERSECTION=D1
set CODE=B
for %%S in (PM1 PM2 PM3 PM4 PM5 PM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)

@REM set INTERSECTION=D3
@REM set CODE=E
@REM for %%S in (AM1 AM2 AM3 AM4 AM5 AM6 PM1 PM2 PM3 PM4 PM5 PM6) do (
@REM     echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM     python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM )

@REM set INTERSECTION=D4
@REM set CODE=F
@REM for %%S in (AM1 AM2 AM3 AM4 AM5 AM6 PM1 PM2 PM3 PM4 PM5 PM6) do (
@REM     echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM     python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM )

GOTO:skip2
set INTERSECTION=D2
set CODE=C
for %%S in (AM1 AM2 AM3 AM4 AM5 AM6 PM1 PM2 PM3 PM4 PM5 PM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)
:skip2


set DATE=2025-09-29

GOTO:skip3
set INTERSECTION=D1
set CODE=A
for %%S in (AM1 AM2 AM3 AM4 AM5 AM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)

set INTERSECTION=D1
set CODE=C
for %%S in (PM1 PM2 PM3 PM4 PM5 PM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)

set INTERSECTION=D2
set CODE=B
for %%S in (AM1 AM2 AM3 AM4 AM5 AM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)
:skip3

@REM set INTERSECTION=D2
@REM set CODE=E
@REM for %%S in (PM1 PM2 PM3 PM4 PM5 PM6) do (
@REM     echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM     python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM )



set DATE=2025-09-30

GOTO:skip4
set INTERSECTION=D1
set CODE=G
for %%S in (AM1 AM2 AM3 AM4 AM5 AM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)

set INTERSECTION=D2
set CODE=F
for %%S in (AM1 AM2 AM3 AM4 AM5 AM6) do (
    echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
    python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
)
:skip4

@REM set INTERSECTION=D1
@REM set CODE=H
@REM for %%S in (PM1 PM2 PM3) do (
@REM     echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM     python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM )

@REM set INTERSECTION=D2
@REM set CODE=I
@REM for %%S in (PM1 PM2 PM3) do (
@REM     echo Running: %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM     python main_coordinate_transform.py %DATE% %VEH_TYPE% %INTERSECTION% %CODE% %%S %SUBSAMPLED_FLAG% %DEBUG_FLAG%
@REM )
